version: "3.9"

services:
  db:
    image: postgres:16 
    container_name: toxicpair-postgres
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: toxicpair
    ports:
      - "5433:5432"   # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d toxicpair"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
