import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { AuthProvider } from "./lib/auth";
import App from "./App";
import "./index.css";
const qc = new QueryClient();
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsxs(QueryClientProvider, { client: qc, children: [_jsx(AuthProvider, { children: _jsx(BrowserRouter, { children: _jsx(App, {}) }) }), _jsx(ReactQueryDevtools, { initialIsOpen: false })] }) }));
